In [32]:
import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/annotations_final.txt")
df

,id,title,selftext,labels,disorder,text
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d..."
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ..."
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...
...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel..."
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...

In [33]:
df2=df["text"]

In [34]:
df2

0       I cut myself for the first time in a year toda...
1       Anybody hate springsummer. And even so, when d...
2       So Im staring at this tablet of Lexapro. and I...
3       Found a poem sort of thing, very emo ha ha ha ...
4       You dont get it. It gets better Stop thinking ...
                              ...
2867    My life just feels like this one big party Im ...
2868    Just move away from your parents. You probably...
2869    That feeling when. You wake up, and that itsel...
2870    Life just keeps getting more complicated. You ...
2871    This is how I look like. my eyes are ususally ...
Name: text, Length: 2872, dtype: object

In [35]:
df2[2870]

'Life just keeps getting more complicated. You would think after years of bad breaks, something good would come into your life and stay but in reality the world owes you nothing and will chew you up and spit you out if you let it and i do. I dont feel like Im strong enough to be a part of the life i was dealt with.i am so frustrated and full of anxiety that i am always clenching my teeth and hold my breath. I think it got so bad that it caused my sleep apnea to get worse. I just dont know what to do anymore. I have these really depressive episodes from time to time and i cant seem to control my emotions anymore. When it gets really bad i have a total mental breakdown. I want all this pain to finally end. Cant go another year go by wasted being miserable and hopeless. I just cant.'

In [36]:
!pip install --upgrade openai

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openai in /usr/local/lib/python3.8/dist-packages (0.27.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from openai) (4.64.1)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.8/dist-packages (from openai) (2.25.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.8/dist-packages (from openai) (3.8.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.20->openai) (1.26.14)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.20->openai) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.20->openai) (2022.12.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.20->openai) (2.10)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp->openai) (6.0.4)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->openai) (22.2.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->openai) (3.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.8/dist-packages (from aiohttp->openai) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->openai) (1.8.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.8/dist-packages (from aiohttp->openai) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from aiohttp->openai) (1.3.3)

In [37]:
import os
import openai

api_key='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'
openai.api_key = api_key

In [38]:
df2[0]

'I cut myself for the first time in a year today. and hated that I still loved it. The burning sensation from the blade on my arm and leg. I didnt even cut deep, I barely bled, but the feeling was still almost the same, but without the kick of seeing my own blood trail down my limbs staining the covers in my bed. I told myself that I was only going to cut a few times, but here I am with surely thirty new scars on my body. I fucking hate myself.'

In [39]:
df

,id,title,selftext,labels,disorder,text
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d..."
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ..."
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...
...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel..."
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...

In [40]:
display(df.iloc[2690])

id                                                     eu2jzp
title                                                 Venting
selftext    This is probably going to look like the most s...
labels                                                 [0, 1]
disorder                                 {'anxiety_disorder'}
text        Venting. This is probably going to look like t...
Name: 2690, dtype: object

In [41]:
examples = df.groupby('labels').apply(lambda x: x.sample(1))
print(examples)

                 id                                         title  \
labels
[0, 0] 2665  ctqk2x                       Widsom teeth extraction
[0, 1] 745   5vbzrp        Is anyone else scared to make friends?
[1, 0] 1653  5nds9s                  I just want to be left alone
[1, 1] 1915  ei3pw1  How often does depression skip a generation?

                                                      selftext  labels  \
labels
[0, 0] 2665  This friday im getting rid of my four widsom m...  [0, 0]
[0, 1] 745   I can count on one hand the people who have al...  [0, 1]
[1, 0] 1653  I'm a junior in college in my second day of cl...  [1, 0]
[1, 1] 1915  Im not sure about my grandparents but I suspec...  [1, 1]

                                                disorder  \
labels
[0, 0] 2665                            {'control_group'}
[0, 1] 745                          {'anxiety_disorder'}
[1, 0] 1653                      {'depressive_disorder'}
[1, 1] 1915  {'depressive_disorder', 'anxiety_disorder'}

                                                          text
labels
[0, 0] 2665  Widsom teeth extraction. This friday im gettin...
[0, 1] 745   Is anyone else scared to make friends. I can c...
[1, 0] 1653  I just want to be left alone. Im a junior in c...
[1, 1] 1915  How often does depression skip a generation. I...

In [42]:
import openai

api_key='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'
openai.api_key = api_key

examples = [
    (df2[0], "depressive_disorder"),
    (df2[1], "depressive_disorder_and_anxiety_disorder"),
    (df2[2690], "anxiety_disorder"),
    (df2[2870], "Neither_depressive_disorder_nor_anxiety_disorder")
]

# Add the examples to the prompt
prompt = "Label the following sentences into one of these categories: depressive_disorder, depressive_disorder_and_anxiety_disorder, anxiety_disorder, Neither_depressive_disorder_nor_anxiety_disorder.\n\n"
for input, output in examples:
    prompt += f"Text: {input}\nLabel: {output}\n\n"

# Add some new data to label
prompt += df2[31]+"\nLabel:"
print(prompt)

# Ask GPT-3 to complete the prompt
response = openai.Completion.create(
    engine="text-davinci-003",
    prompt=prompt,
    stop="\n",
    temperature=0,
    max_tokens=100
)
print(response)
print(response["choices"][0]["text"])

Label the following sentences into one of these categories: depressive_disorder, depressive_disorder_and_anxiety_disorder, anxiety_disorder, Neither_depressive_disorder_nor_anxiety_disorder.

Text: I cut myself for the first time in a year today. and hated that I still loved it. The burning sensation from the blade on my arm and leg. I didnt even cut deep, I barely bled, but the feeling was still almost the same, but without the kick of seeing my own blood trail down my limbs staining the covers in my bed. I told myself that I was only going to cut a few times, but here I am with surely thirty new scars on my body. I fucking hate myself.
Label: depressive_disorder

Text: Anybody hate springsummer. And even so, when depression is not too severe? Right now we are having some sunny days here in my country of Denmark, and very mild, almost spring weather, and I hate i.The thought that springsummer is on the way makes me depressed and anxious.I wish I could enjoy it but I dont.Everybody around me is going on and on about how nice the weather is and how it makes your mood better., and I either have to fake agreement or simply shut up when folks around me start talking about the weather. My mood gets worse in sunny springsummer weather.I am most stable depressionwise when it is cloudy and more grey.probably makes no sense. Anybody else?
Label: depressive_disorder_and_anxiety_disorder

Text: Venting. This is probably going to look like the most stupid thing youve read, but here it goes for the past 5 years I felt so fricking bad, my whole life has turned to complete shit, my ocd had gotten so bad for so long I stayed at home for almost 2 years straight. I have struggled with doctors, medication,abusive parents, I went through hell and still I want to believe I kept at least a little bit of my sanity intact from all this. The thing is, right now, right this minute I just realized, I lost 5 years. 5 years of my life that Im never getting back. I lost opportunities, I lost people I could have met and be with, I lost friendships, laughters, so many good things, just like all those good things anxiety is taking from me for so long. And I honestly hadnt even realized until now, when I saw a classmate of mine who is done with his studies when Im only still in the beginning. Im just wondering where does it stop? When does ocd and anxiety altogether stop stealing your life? Is it too much to just want to live a happy life, nothing too much, just the right things, be surrounded by people who love me, or just simply be able to love myself? I just need for once, just once, to feel what it feels like to be free
Label: anxiety_disorder

Text: Life just keeps getting more complicated. You would think after years of bad breaks, something good would come into your life and stay but in reality the world owes you nothing and will chew you up and spit you out if you let it and i do. I dont feel like Im strong enough to be a part of the life i was dealt with.i am so frustrated and full of anxiety that i am always clenching my teeth and hold my breath. I think it got so bad that it caused my sleep apnea to get worse. I just dont know what to do anymore. I have these really depressive episodes from time to time and i cant seem to control my emotions anymore. When it gets really bad i have a total mental breakdown. I want all this pain to finally end. Cant go another year go by wasted being miserable and hopeless. I just cant.
Label: Neither_depressive_disorder_nor_anxiety_disorder

A poem about depression. My Tormentor, Depression You take me down to the depths And leave me there, halfconscious and bare In your grasp. How strong are you really? Not very. I know youre weak But you sneak up behind me And attack when I least suspect you. When that happens, I dont want to fight. I want to lose I want you to take me. And that is why you always win. You take away from me happiness and sadness alike Make me indifferent between good and bad Even rob me of my will to live. To you I yield my tormentor. I am at your mercy. What do you want from me? How much deeper will you take me? Suddenly, you let me go, and I swim to the surface I gasp and breathe in the air of hope, and just for a moment I think that maybe everything is going to be okay. Then you grab my leg, and pull me back down You show me hope only to take it away from me Only to make my suffering worse To you I yield, my tormentor.
Label:
{
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "logprobs": null,
      "text": " depressive_disorder"
    }
  ],
  "created": 1677999657,
  "id": "cmpl-6qceXwp7JNdshb2gJdATMf9Lu7d9s",
  "model": "text-davinci-003",
  "object": "text_completion",
  "usage": {
    "completion_tokens": 4,
    "prompt_tokens": 1038,
    "total_tokens": 1042
  }
}
 depressive_disorder