In [1]:
import pandas as pd
import ast
from tqdm import tqdm

# Get nan outputs

In [2]:
main_df = pd.read_csv("../data/test/full_test.csv")
main_df

,id,title,selftext,labels,disorder,text,groundtruth_label
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety)
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety)
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety)
...,...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,Depression
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,Normal
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...",Normal
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,Normal
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,Normal

In [3]:
SEED=0
# MODEL="gpt-3.5-turbo"
MODEL="gpt-4"
PROMPT_TYPE="depression_mards"

df = pd.read_csv(f"../results/zero_shot/zero_shot_{PROMPT_TYPE}_{MODEL}_seed_{SEED}_old.csv")
print(df.shape)
df.dropna(subset=[f'results_{PROMPT_TYPE}_{MODEL}']).shape

(2872, 8)

(2841, 8)

# Combine new and old csv

In [4]:
main_df = pd.read_csv("../data/test/full_test.csv")
main_df

,id,title,selftext,labels,disorder,text,groundtruth_label
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety)
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety)
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety)
...,...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,Depression
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,Normal
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...",Normal
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,Normal
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,Normal

In [5]:
SEED=0
# MODEL="gpt-3.5-turbo"
MODEL="gpt-4"
PROMPT_TYPE="depression_mards"

df = pd.read_csv(f"../results/zero_shot/zero_shot_{PROMPT_TYPE}_{MODEL}_seed_{SEED}_old.csv")
print(df.shape)
df = df.dropna(subset=[f'results_{PROMPT_TYPE}_{MODEL}']).reset_index(drop=True)
df.shape

(2872, 8)

(2841, 8)

In [6]:
df_new = pd.read_csv(f"../results/zero_shot/zero_shot_{PROMPT_TYPE}_{MODEL}_seed_{SEED}_new.csv")
df_new.shape

(31, 8)

In [7]:
result_dict = dict()
for i in range(len(df)):
    key = df.at[i, f'id']
    val = df.at[i, f'results_{PROMPT_TYPE}_{MODEL}']
    result_dict[key] = val
    
for i in range(len(df_new)):
    key = df_new.at[i, f'id']
    val = df_new.at[i, f'results_{PROMPT_TYPE}_{MODEL}']
    result_dict[key] = val
    
len(result_dict)

2872

In [8]:
main_df[f'results_{PROMPT_TYPE}_{MODEL}'] = main_df['id'].apply(lambda x: result_dict[x])
main_df

,id,title,selftext,labels,disorder,text,groundtruth_label,results_depression_mards_gpt-4
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression,"{\n""1.Apparent Sadness"": 6,\n""2.Reported sadne..."
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety),"{\n""1"": 2,\n""2"": 3,\n""3"": 4,\n""4"": 0,\n""5"": 0,..."
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety),"{\n""1"": 2,\n""2"": 3,\n""3"": 3,\n""4"": 2,\n""5"": 3,..."
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression,"{\n""1"": 4,\n""2"": 5,\n""3"": 5,\n""4"": 2,\n""5"": 2,..."
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety),"{\n""1"": 6,\n""2"": 6,\n""3"": 6,\n""4"": 0,\n""5"": 0,..."
...,...,...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,Depression,"{\n""1"": 4,\n""2"": 6,\n""3"": 5,\n""4"": 3,\n""5"": 2,..."
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,Normal,"{\n""1"": 3,\n""2"": 4,\n""3"": 5,\n""4"": 2,\n""5"": 2,..."
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...",Normal,"{\n""1"": 6,\n""2"": 6,\n""3"": 6,\n""4"": 0,\n""5"": 0,..."
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,Normal,"{\n""1"": 4,\n""2"": 5,\n""3"": 5,\n""4"": 4,\n""5"": 2,..."
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,Normal,"{\n""1"": 4,\n""2"": 4,\n""3"": 5,\n""4"": 6,\n""5"": 0,..."

In [9]:
main_df.to_csv(f"../results/zero_shot/zero_shot_{PROMPT_TYPE}_{MODEL}_seed_{SEED}.csv", index=False)

In [10]:
df = pd.read_csv(f"../results/zero_shot/zero_shot_{PROMPT_TYPE}_{MODEL}_seed_{SEED}.csv")
print(df.shape)
df = df.dropna(subset=[f'results_{PROMPT_TYPE}_{MODEL}']).reset_index(drop=True)
df.shape

(2872, 8)

(2872, 8)