In [12]:
import pandas as pd
import ast
from tqdm import tqdm

In [3]:
df = pd.read_csv("../results/zero_shot/zero_shot_depression_mental_llm_gpt-3.5-turbo_seed_0.csv")
df

,id,title,selftext,labels,disorder,text,results_depression_mental_llm_gpt-3.5-turbo
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,"Based on the content of the post, it is possib..."
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...","Based on the information provided in the post,..."
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,"Based on the information provided in the post,..."
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...","Based on the content of the post, it is possib..."
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,"Based on the content of the post, it is highly..."
...,...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,"Based on the content of the post, it is highly..."
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,"Based on the information provided in the post,..."
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...","Based on the content of the post, it is highly..."
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,"Based on the information provided in the post,..."
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,"Based on the information provided in the post,..."

In [4]:
df = pd.read_csv("../results/zero_shot/zero_shot_depression_anxiety_comorbidity_gpt-3.5-turbo_seed_0.csv")
df

,id,title,selftext,labels,disorder,text,results_depression_anxiety_comorbidity_gpt-3.5-turbo
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,"{'depression': 'yes', 'anxiety': 'yes'}"
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...","{'depression': 'yes', 'anxiety': 'yes'}"
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,"{'depression': 'yes', 'anxiety': 'yes'}"
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...","{'depression': 'yes', 'anxiety': 'yes'}"
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,"{'depression': 'yes', 'anxiety': 'yes'}"
...,...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,"{'depression': 'yes', 'anxiety': 'no'}"
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,"{'depression': 'yes', 'anxiety': 'yes'}"
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...","{'depression': 'yes', 'anxiety': 'yes'}"
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,"{'depression': 'yes', 'anxiety': 'yes'}"
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,"{'depression': 'yes', 'anxiety': 'yes'}"

In [8]:
results = df['results_depression_anxiety_comorbidity_gpt-3.5-turbo']
len(results)

2872

In [19]:
depression = 0
anxiety = 0
invalid = 0
total = 0
for result in tqdm(results):
    try:
        result = ast.literal_eval(result)
        if result['depression'].lower() == "yes":
            depression += 1

        if result['anxiety'].lower() == "yes":
            anxiety += 1

        total += 1
    
    except:
        invalid += 1

depression, (depression/total), anxiety, (anxiety/total)

100%|██████████████████████████████████████████████████████████████████████████████████| 2872/2872 [00:00<00:00, 49120.20it/s]

(2587, 0.9013937282229966, 2339, 0.8149825783972126)