In [1]:
import pandas as pd
import ast
from tqdm import tqdm

In [2]:
main_df = pd.read_csv("../data/test/full_test.csv")
main_df

,id,title,selftext,labels,disorder,text,groundtruth_label
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety)
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety)
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety)
...,...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,Depression
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,Normal
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...",Normal
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,Normal
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,Normal

In [3]:
df = pd.read_csv("../results/zero_shot/zero_shot_depression_anxiety_comorbidity_gpt-3.5-turbo_seed_0.csv")
print(df.shape)
df.dropna(subset=['results_depression_anxiety_comorbidity_gpt-3.5-turbo']).shape

(2872, 7)

(2872, 7)

In [4]:
df = pd.read_csv("../results/zero_shot/zero_shot_depression_anxiety_comorbidity_gpt-4_seed_0.csv")
print(df.shape)
df.dropna(subset=['results_depression_anxiety_comorbidity_gpt-4']).shape

(2872, 8)

(2872, 8)

In [21]:
ids = df[df['results_depression_naive_gpt-4'].isnull()]['id'].tolist()
ids

['c32kf6',
 'dx4nn5',
 '4mfd88',
 '5imvgl',
 'db88h2',
 'fkai97',
 'bzbdrp',
 '611d2l',
 'gxwbra',
 '6qc2ww',
 'fg2pt7',
 '7hp8ir',
 '5dqwph',
 '67jylm',
 'ifvuwd',
 '7veicr',
 '5bbg6f',
 'ex82du',
 'gnmvb0',
 '474v69',
 '7sedju',
 'heqbf5',
 '71uogc',
 '7190co',
 'ck8nqc',
 'c2wasr',
 'gre6fb',
 '9supxf',
 'ocid30',
 'big2mx',
 '7wr5xn',
 'blzt8p',
 '687l8b',
 'kblv7h',
 '44f3ai',
 '5riov8',
 'astplx',
 '4tpfcs',
 'gix5fy',
 'fuati2',
 '5pf7th',
 'biciqq',
 '4folzf',
 '4sih9f',
 '6owyg0',
 '7ep4q7',
 'f38cfi',
 'db0uwb',
 'lo2ym5',
 '7pi1nq',
 'hc1lak',
 'bcjvv6',
 'ho69tc',
 'gq9w52',
 '7qr21e',
 'a2uokq',
 'jt1hzm',
 '6vubzc',
 '4d2x50',
 'czeavp',
 '7brise',
 '537yo3',
 '8q7pzm',
 '5j2905',
 'cnjig5',
 'o8yxbm',
 'fwdozm',
 'el6nds',
 '9838f4',
 '5pgu2k',
 '7ls864',
 'g6d2u9',
 '8jy0v0',
 'd3sw6z',
 'e7lwnw',
 'fo5jgn',
 'f9x7c9',
 '4tvkcz',
 'a5hkbz',
 '54mbo4',
 'fx3tbj',
 '886ixu',
 '9nxon9',
 'cwgyt6',
 'fenp1k',
 '8m3zbj',
 '4st12q',
 'g9fl2h',
 '9aibv6',
 'e0ervg',
 'h79fkn',
 'c0y0bp',
 '70ryy3',
 'by9gnp',
 '5x10a6',
 'mujqud',
 'c3oale',
 'c40whm',
 '5dx5g8',
 'dqobl3',
 'g4gwd9',
 'he35v2',
 '9c9wog',
 'em2iwj',
 'cyps11',
 'blcrp1',
 '43ma3n',
 '9efcpi',
 '7wp935',
 'ei6090',
 'gbsxp3',
 'fb74ll',
 'a9166x',
 '4rl9s4',
 'eu7wc6',
 '9kacqu',
 'gvftbv',
 '755unn',
 '82vb72',
 '5ou37v',
 'bojtmd',
 '8xjhrm',
 '7d6wlo',
 '6qbrjb',
 'ol78lq',
 'iv6xci',
 'adr5ac',
 'azcx97',
 '5i1nh1',
 'jy7jgm',
 '4s1sm6',
 'bdf3ed',
 'en090a',
 'e5ddgy',
 'azb617',
 '8jsnih',
 '4bjehi',
 'azjah5',
 'efziz0',
 'm1d4ds',
 'jqg12s',
 'jq9zri',
 'og1wje',
 'i16ski',
 'a4tx9g',
 '44pqhw',
 '947h2s',
 '6ejwtr',
 '55bz7a',
 'jvncdv',
 'beny5c',
 'ab3sod',
 'aa6go0',
 'c2n2fz',
 'b21lak',
 'htbwyv',
 '6pmcx3',
 'afhbny',
 '63vh2v',
 '6hxme5',
 'd8qys9',
 '8ml82k',
 'icvrcz',
 'cv7yd2',
 '5wvdel',
 'dqbun0',
 'e6db0a',
 '9dbf4a',
 '4fuq5t',
 'ejqz6d',
 '6n6rhk',
 '96i282',
 '5tlsmx',
 'fbcauo',
 'ctatl2',
 '732nvq',
 '4r0ljt',
 'c1wtji',
 'gk7yh5',
 '7bsqsw',
 '6464aq',
 '6zsykl',
 'e9vgtl',
 '9j8w6b',
 'fe4i9k',
 'hrzj6z',
 'era89r',
 'hcfib6',
 'eag0ec',
 '6vw1lf',
 '88polj',
 '4ah1fm',
 'd7mshq',
 '4bkhn6',
 '7162mv',
 '45icj5',
 '7c0uo1',
 'imzdxd',
 'hkn082',
 '427c5e',
 '447a23',
 '5g62ah',
 '6nt4o4',
 '69xxj4',
 'dotoyq',
 'exed9y',
 'buiq5b',
 'a2wjm3',
 'aoy296',
 'bivx2i',
 '5wlfzz',
 '41mwbz',
 '6cevk3',
 'aqxgzr',
 'hadz9o',
 'abgk30',
 'okg1tx',
 '9443um',
 '4lxo62',
 'abrri8',
 'bwlyyk',
 '90qzgi',
 'o45dn3',
 'cc5pc9',
 'bx4xig',
 'dienn6',
 '91jb7a',
 'hayvu5',
 'ih9h5z',
 'esm95r',
 'g5oaau',
 'aewlnx',
 'hv0g7g',
 '5p984j',
 'aq1ryu',
 '5mcnpm',
 '65e80k',
 'bjl70u',
 '9lvw94',
 '4x88k2',
 '9i8x1t',
 '7p98jn',
 '54ekdj',
 'em3fnq',
 'icm99n',
 '7lkyxt',
 '9ze2zf',
 'faiehr',
 '9nfqs4',
 '7m4m6j',
 '73gt2x',
 'nn34eu',
 'ns8uo7',
 '59nm3k',
 '9h89u0',
 '7irndb',
 'h9owcv',
 'a7rmov',
 '9fhk16',
 '98f3c6',
 'e4qw91',
 'byz3om',
 'fkg8i2',
 '63ut60',
 '87zmq8',
 '50ws18',
 '9x6x0u',
 '7m5wic',
 'b6r7d9',
 'ib2l3e',
 'hq8ela',
 '6h7hp3',
 '9s3fjp',
 'dl9fpa',
 '4u6mqs',
 '7s5d7t',
 '4518s8',
 '6nm769',
 '5lvk7c',
 'byk9wb',
 '82bnve',
 '96bj0l',
 '48j8h2',
 'g85fxb',
 'c5jsmh',
 '8ht802',
 '5sidtp',
 '6r7137',
 'gpql4s',
 'ch8mtq',
 'e5o4hs',
 'gvbeje',
 'g0ofod',
 '5cogdc',
 'b3hmzu',
 '9a0jm9',
 'd5nfn3',
 '4lonno',
 '9b6e9j',
 'ar8ifk',
 '7h9e1j',
 'f7ywrr',
 '6rzoq3',
 'ipb6mn',
 '7xc8qq',
 'hp8uuh',
 'ih553y',
 '8irhj6',
 'dhrc28',
 '440x15',
 'ionei4',
 'ju2mdz',
 'ay46ld',
 '9lif0k',
 'j95vbk',
 '7itzr4',
 '7l8yqh',
 '41uoxj',
 'lm7uix',
 '4pfk9x']

In [24]:
new_df = main_df[main_df['id'].isin(ids)].reset_index(drop=True)
new_df

,id,title,selftext,labels,disorder,text,groundtruth_label
0,c32kf6,Never been so unhealthy mentally and physically.,(18m) About 5 months ago I was the happiest an...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Never been so unhealthy mentally and physicall...,Comorbid (Depression + Anxiety)
1,dx4nn5,What haunts you?(a thread if you want to add t...,(23f if anyone cares) My mom mentally and emot...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",What haunts you?a thread if you want to add to...,Comorbid (Depression + Anxiety)
2,4mfd88,Episodes of Atypical Depression vs Episodes of...,**My understanding:**\r\n \r\n 1. **Major Depr...,"[0, 0]",{'control_group'},Episodes of Atypical Depression vs Episodes of...,Normal
3,5imvgl,I wish I had the ability to crawl out of my sk...,**Trapped** because **things don't work correc...,"[1, 0]",{'depressive_disorder'},I wish I had the ability to crawl out of my sk...,Depression
4,db88h2,I need some help,"&#x200B;\r\n \r\n Hello, so I have been diagno...","[1, 0]",{'depressive_disorder'},"I need some help. x200B Hello, so I have been ...",Depression
...,...,...,...,...,...,...,...
315,7itzr4,helpless. even my mother hates me.,yesterday i overheard my mother talking to my ...,"[0, 0]",{'control_group'},helpless. even my mother hates me. yesterday i...,Normal
316,7l8yqh,diagnosed.,yesterday my psychologist diagnosed me with hy...,"[0, 0]",{'control_group'},diagnosed. yesterday my psychologist diagnosed...,Normal
317,41uoxj,The likeness between Depression and Dark Souls 2.,"You are truly alone in this world, in the sens...","[0, 0]",{'control_group'},The likeness between Depression and Dark Souls...,Normal
318,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,Depression
319,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,Normal

In [5]:
df = pd.read_csv("../results/zero_shot/zero_shot_anxiety_naive_gpt-4_seed_0_old.csv")
print(df.shape)
df.dropna().shape

(2872, 7)

(2556, 7)

In [19]:
# depression = 0
# anxiety = 0
# invalid = 0
# total = 0
# for result in tqdm(results):
#     try:
#         result = ast.literal_eval(result)
#         if result['depression'].lower() == "yes":
#             depression += 1

#         if result['anxiety'].lower() == "yes":
#             anxiety += 1

#         total += 1
    
#     except:
#         invalid += 1

# depression, (depression/total), anxiety, (anxiety/total)

100%|██████████████████████████████████████████████████████████████████████████████████| 2872/2872 [00:00<00:00, 49120.20it/s]

(2587, 0.9013937282229966, 2339, 0.8149825783972126)