In [1]:
import pandas as pd
import ast
from tqdm import tqdm
import os

In [10]:
result_dir = "../results/few_shot"
result_files = [os.path.join(result_dir, file) for file in os.listdir(result_dir) if ".csv" in file]
result_files

['../results/few_shot/few_shot_depression_gpt-3.5-turbo_num_examples_2_seed_0.csv',
 '../results/few_shot/few_shot_depression_gpt-4_num_examples_2_seed_0.csv',
 '../results/few_shot/few_shot_anxiety_gpt-4_num_examples_2_seed_0.csv',
 '../results/few_shot/few_shot_comorbidity_gpt-3.5-turbo_num_examples_1_seed_0.csv',
 '../results/few_shot/few_shot_anxiety_gpt-3.5-turbo_num_examples_2_seed_0.csv']

In [11]:
for file in result_files:
    df = pd.read_csv(file)
    org_size = len(df)
    if len(df.dropna()) != org_size:
        print(file)

# Get nan outputs

In [2]:
main_df = pd.read_csv("../data/test/full_test.csv")
main_df

,id,title,selftext,multilabel_clf_label,disorder,text,multiclass_clf_label,depression_label,anxiety_label
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression,1,0
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety),1,1
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety),1,1
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression,1,0
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety),1,1
...,...,...,...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,Depression,1,0
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,Normal,0,0
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...",Normal,0,0
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,Normal,0,0
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,Normal,0,0

In [23]:
SEED=0
NUM_EXAMPLES_PER_LABEL=1

MODEL="gpt-3.5-turbo"
# MODEL="gpt-4"
PROMPT_TYPE="comorbidity"

df = pd.read_csv(f"../results/few_shot/few_shot_{PROMPT_TYPE}_{MODEL}_num_examples_{NUM_EXAMPLES_PER_LABEL}_seed_{SEED}.csv")
print(df.shape)
print(df.dropna().shape)
df[f'results_{PROMPT_TYPE}_{MODEL}'].isna().sum()

(2872, 12)
(2870, 12)

2

In [12]:
[i for i, x in enumerate(df['results_comorbidity_gpt-3.5-turbo'].isna()) if x]

[1532, 2379]

# Combine new and old csv

In [2]:
main_df = pd.read_csv("../data/test/full_test.csv")
main_df

,id,title,selftext,multilabel_clf_label,disorder,text,multiclass_clf_label,depression_label,anxiety_label
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression,1,0
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety),1,1
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety),1,1
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression,1,0
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety),1,1
...,...,...,...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,Depression,1,0
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,Normal,0,0
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...",Normal,0,0
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,Normal,0,0
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,Normal,0,0

In [3]:
SEED=0
NUM_EXAMPLES_PER_LABEL=2

# MODEL="gpt-3.5-turbo"
MODEL="gpt-4"
PROMPT_TYPE="depression"

df = pd.read_csv(f"../results/few_shot/few_shot_{PROMPT_TYPE}_{MODEL}_num_examples_{NUM_EXAMPLES_PER_LABEL}_seed_{SEED}_old.csv")
print(df.shape)
df = df.dropna().reset_index(drop=True)
df

(2872, 10)

,id,title,selftext,multilabel_clf_label,disorder,text,multiclass_clf_label,depression_label,anxiety_label,results_depression_gpt-4
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression,1,0,{'depression': 'yes'}
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety),1,1,{'depression': 'yes'}
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety),1,1,{'depression': 'yes'}
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression,1,0,{'depression': 'yes'}
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety),1,1,{'depression': 'yes'}
...,...,...,...,...,...,...,...,...,...,...
2857,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,Depression,1,0,{'depression': 'yes'}
2858,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,Normal,0,0,{'depression': 'yes'}
2859,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...",Normal,0,0,{'depression': 'yes'}
2860,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,Normal,0,0,{'depression': 'yes'}
2861,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,Normal,0,0,{'depression': 'yes'}

In [4]:
df_new = pd.read_csv(f"../results/few_shot/few_shot_{PROMPT_TYPE}_{MODEL}_num_examples_{NUM_EXAMPLES_PER_LABEL}_seed_{SEED}_new.csv")
df_new.shape

(10, 12)

In [5]:
result_dict = dict()
for i in range(len(df)):
    key = df.at[i, f'id']
    val = df.at[i, f'results_{PROMPT_TYPE}_{MODEL}']
    result_dict[key] = val
    
for i in range(len(df_new)):
    key = df_new.at[i, f'id']
    val = df_new.at[i, f'results_{PROMPT_TYPE}_{MODEL}']
    result_dict[key] = val
    
len(result_dict)

2872

In [6]:
main_df[f'results_{PROMPT_TYPE}_{MODEL}'] = main_df['id'].apply(lambda x: result_dict[x])
main_df

,id,title,selftext,multilabel_clf_label,disorder,text,multiclass_clf_label,depression_label,anxiety_label,results_depression_gpt-4
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression,1,0,{'depression': 'yes'}
1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety),1,1,{'depression': 'yes'}
2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety),1,1,{'depression': 'yes'}
3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression,1,0,{'depression': 'yes'}
4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety),1,1,{'depression': 'yes'}
...,...,...,...,...,...,...,...,...,...,...
2867,lm7uix,My life just feels like this one big party Im ...,You know the feeling. Where youre just so over...,"[1, 0]",{'depressive_disorder'},My life just feels like this one big party Im ...,Depression,1,0,{'depression': 'yes'}
2868,ac1aj9,Just move away from your parents!,You probably want to hear my sob story as much...,"[0, 0]",{'control_group'},Just move away from your parents. You probably...,Normal,0,0,{'depression': 'yes'}
2869,hng1f5,That feeling when...,"You wake up, and that itself just brings you s...","[0, 0]",{'control_group'},"That feeling when. You wake up, and that itsel...",Normal,0,0,{'depression': 'yes'}
2870,4pfk9x,Life just keeps getting more complicated,"You would think after years of bad breaks, som...","[0, 0]",{'control_group'},Life just keeps getting more complicated. You ...,Normal,0,0,{'depression': 'yes'}
2871,ae5lum,This is how I look like:,my eyes are ususally very red because of the t...,"[0, 0]",{'control_group'},This is how I look like. my eyes are ususally ...,Normal,0,0,{'depression': 'yes'}

In [7]:
main_df.to_csv(f"../results/few_shot/few_shot_{PROMPT_TYPE}_{MODEL}_num_examples_{NUM_EXAMPLES_PER_LABEL}_seed_{SEED}.csv", index=False)

In [8]:
df = pd.read_csv(f"../results/few_shot/few_shot_{PROMPT_TYPE}_{MODEL}_num_examples_{NUM_EXAMPLES_PER_LABEL}_seed_{SEED}.csv")
print(df.shape)
df = df.dropna(subset=[f'results_{PROMPT_TYPE}_{MODEL}']).reset_index(drop=True)
df.shape

(2872, 10)

(2872, 10)