In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import precision_recall_fscore_support

In [2]:
def generate_label(preds_str):
    if "yes" in preds_str.lower():
        return 1
    elif "no" in preds_str.lower():
        return 0
    else:
     return -1

# Zero Shot

In [3]:
seed=1
# data_type = "depression"
data_type = "anxiety"

model = "llama_chat_7b"
# model = "llama_chat_13b"

df = pd.read_csv(f"../results/zero_shot/zero_shot_{data_type}_llama_{model}_seed_{seed}_v{seed}.csv")
df['preds'] = [generate_label(str(pred).replace("\n", "")) for pred in df[f"results_{data_type}_llama_{model}"]]
print(df["preds"].value_counts())

preds
 1    1478
 0    1201
-1     193
Name: count, dtype: int64

In [4]:
df = pd.read_csv(f"../results/zero_shot/zero_shot_{data_type}_{model}_seed_{seed}_v{seed}.csv")
df[f"results_{data_type}_{model}"] = df[f"results_{data_type}_{model}"].apply(lambda x: str(x).replace("\n", ""))
df['preds'] = [generate_label(pred) for pred in df[f"results_{data_type}_{model}"]]
print(df["preds"].value_counts())

preds
 1    2826
 0      40
-1       6
Name: count, dtype: int64

In [7]:
precision, recall, fscore, support = precision_recall_fscore_support(y_true=df['depression_label'].tolist(), y_pred=df['preds'].tolist(), average="macro")
results = {
    "precision": precision,
    "recall": recall,
    "fscore": fscore,
}
results

/home/atharvak/miniconda3/envs/mentallm_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

{'precision': 0.3840056617126681,
 'recall': 0.3355095175610671,
 'fscore': 0.24809834694769037}

# Few Shot

In [3]:
seed=2
data_type = "depression"
df = pd.read_csv("../results/few_shot/few_shot_depression_llama_chat_7b_num_examples_ss_2_v1_seed_1_xyz.csv")
# df = pd.read_csv(f"../results/few_shot/few_shot_{data_type}_mental_llama_chat_7b_num_examples_ss_2_v{seed}_seed_{seed}.csv")
df

,index,id,title,selftext,multilabel_clf_label,disorder,text,multiclass_clf_label,depression_label,anxiety_label,few_shot_prompt_depression,exemplar_labels_depression,results_depression_llama_chat_7b
0,0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression,1,0,"\nPost: so, ive been inactive on this account ...","['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
1,1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety),1,1,\nPost: i just have to accept that im depresse...,"['Yes, the poster suffers from depression.', '...","\nYes, the poster suffers from depression.\n\n..."
2,2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety),1,1,"\nPost: help me, please. give me some advice o...","['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
3,3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression,1,0,\nPost: i just want to start this off by sayin...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
4,4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety),1,1,\nPost: and im just tired of being told it it ...,"['Yes, the poster suffers from depression.', '...",\n\n\n
5,5,8qs81x,People judge my situation too much while knowi...,"""You're not trying hard enough to improve your...","[1, 0]",{'depressive_disorder'},People judge my situation too much while knowi...,Depression,1,0,\nPost: i get this vine and impression by cowo...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
6,6,dpx3i2,I want to die..,(15F) \r\n \r\n Ive always wanted to..that has...,"[1, 0]",{'depressive_disorder'},I want to die. 15F Ive always wanted to.that h...,Depression,1,0,\nPost: ive been meaning to write this for a l...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression.\n\n\n..."
7,7,ez4lqg,im so lethargic,(16f)for the past week i cant seem to have the...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",im so lethargic. 16ffor the past week i cant s...,Comorbid (Depression + Anxiety),1,1,\nPost: ive tried so hard these years to be be...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
8,8,c32kf6,Never been so unhealthy mentally and physically.,(18m) About 5 months ago I was the happiest an...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Never been so unhealthy mentally and physicall...,Comorbid (Depression + Anxiety),1,1,\nPost: hello everyone. i 24f have been diagno...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
9,9,dx4nn5,What haunts you?(a thread if you want to add t...,(23f if anyone cares) My mom mentally and emot...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",What haunts you?a thread if you want to add to...,Comorbid (Depression + Anxiety),1,1,\nPost: my aunt was mentioning she was packing...,"['Yes, the poster suffers from depression.', '...",\nPost: i just realized that my mom has been d...
10,10,8q4fbu,Boss trying to make me present at a conference,"(Background: diagnosed with GAD, depression, p...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Boss trying to make me present at a conference...,Comorbid (Depression + Anxiety),1,1,\nPost: im quitting my job to focus on my heal...,"['No, the poster does not suffer from depressi...","Yes, the poster suffers from depression."
11,11,858cbk,Everything feels so wrong now.,(For all intents and purposes) My name is Dev....,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Everything feels so wrong now. For all intents...,Comorbid (Depression + Anxiety),1,1,\nPost: i am 18 years old and have been burned...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
12,12,dty4lv,I am done,(I am 17yo)\r\n \r\n I have dated one very bea...,"[0, 0]",{'control_group'},I am done. I am 17yo I have dated one very bea...,Normal,0,0,\nPost: i tried going out tonight with my frie...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
13,13,bws4gr,"I don't like myself, even though I know I should","(I am seeing a therapist, but I just need to v...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","I dont like myself, even though I know I shoul...",Comorbid (Depression + Anxiety),1,1,\nPost: i just want to write this down real qu...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression. The p..."
14,14,caro6p,I dont like it when people say they are depressed,(I Know this is a contoversial topic) but anyw...,"[1, 0]",{'depressive_disorder'},I dont like it when people say they are depres...,Depression,1,0,\nPost: anytime ive opened up to someone about...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
15,15,5s5zle,Advice with medication/how to better describe ...,(I posted this in another sub Reddit but I tho...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Advice with medicationhow to better describe s...,Comorbid (Depression + Anxiety),1,1,\nPost: i have been having mental health issue...,"['Yes, the poster suffers from depression.', '...",\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
16,16,avbgr5,Attempted to get HIV/AIDS,(Im a gay guy by the way) I was contemplating ...,"[1, 0]",{'depressive_disorder'},Attempted to get HIVAIDS. Im a gay guy by the ...,Depression,1,0,"\nPost: hi all, i apologise if there is any sp...","['No, the poster does not suffer from depressi...","Yes, the poster suffers from depression."
17,17,9kezif,Ive been refusing treatment for a decade,(On mobile so bear with me)\r\n \r\n I tried c...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Ive been refusing treatment for a decade. On m...,Comorbid (Depression + Anxiety),1,1,"\nPost: i have mental issues, never got diagno...","['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
18,18,6dvr4n,"Thanks social anxiety, I want to die even more...",(See my last post for details)\r\n \r\n I didn...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Thanks social anxiety, I want to die even more...",Comorbid (Depression + Anxiety),1,1,\nPost: i have no one to tell so i just resort...,"['Yes, the poster suffers from depression.', '...",\n\n\n\n
19,19,cha2ht,Just feeling empty,[17 M] I've lived the year doing my best to tr...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Just feeling empty. 17 M Ive lived the year do...,Comorbid (Depression + Anxiety),1,1,\nPost: ive been meaning to write this for a l...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."

In [4]:
index = 8
print(f"{df['few_shot_prompt_depression'][index]}\n{df['results_depression_mental_llama_chat_7b'][index]}")

You will be presented with a post and an assigned label to identify whether the poster shows symptoms of depression. Strictly answer as 'Yes' or 'No' only. Here are two examples:

Post: so. i was in ambulant psychiatric treatment between december 2015 and december 2016 but sadly i did not get better. im now out of school for 1 12 years and just sitting at home. i finally found the courage, called up that psychiatrist that was recommended to me. now im on antidepressants. also called up a psychiatric hospital just 10km away from me and made an appointment for an interview to get a therapy place for the semiambulant hospital go there in the morning and go back home in the evening so i guess its something. ive been getting gradually worse over the course of the last weeks that even my suicidal thoughts came back that i didnt have for 2 years. i also got diagnosed with severe anxiety disorder, severe depression with suicidal tendence and mild ptsd. idk. i could write more but im kind of lacking the energy for that. thanks for reading.
Question: Does the poster suffer from depression?
Answer: Yes, the poster suffers from depression.

Post: hello everyone. i 24f have been diagnosed with depression and anxiety since i was first diagnosed with ms when i was 13. i was really doing well until around 2018 when i began grad school. everything has begun to pile up and i feel all coming down at once. now, i feel so uninterested in everything. quarantine has made it worse, but it was really bad before. i dont shower as much as i should, i sleep until noon and can hardly get out of bed, i am so unmotivated and overweight and i just dont know what to do. i struggle with binge eating and cant seem to get that under control. i do have my first appointment with a psychiatrist tomorrow since my current therapist isnt working out. im on wellbutrin and lexapro pretty high doses and im still struggling so much. i would love any and all advice. tia!
Question: Does the poster suffer from depression?
Answer: Yes, the poster suffers from depression.

Post: Never been so unhealthy mentally and physically. 18m About 5 months ago I was the happiest and healthiest I had ever been in my life enjoying new hobbies in a very good relationship with the love of my life eating really well while also going to the gym regularly. But 5 months ago my whole life crumbled I found out that my girlfriend had cheated on me with my best friend and had all of her friends lie to me for months just to cover there relationship up but everything just went downhill from there. I got diagnosed with manic depression and schizophrenia after i reached out for help at my nearest hospital they have put me on an ssri and a medication called risperidone but it hasnt done much for me at all. I attempted to commit suicide with those pills but woke up the next super ill and it really just made everything worse. I have panic attacks almost daily and have started smoking cigs to cope with it. My parents arent supportive and ive done almost everything on my own since i was 16. My biggest concern right now is i go days without eating and just drink water and i lost 10 pounds which doesnt sound like much but when your 145 pounds and 6ft tall then drop to 135 you can really see the difference ribs I have never done good in school and im not getting any credits this semester because i very rarely left my room for the past 4 months so im in a very bad spot with school. sorry my grammar is awful ive never been good at writing i will respond to any questions asap
Question: Does the poster suffer from depression?
Answer:


Post: I've been on medication for depression for the past 2 years, and have seen multiple

In [2]:
seed=2
data_type = "depression"
df = pd.read_csv(f"../results/few_shot/few_shot_{data_type}_mental_llama_chat_7b_num_examples_ss_2_v{seed}_seed_{seed}.csv")
df

,index,id,title,selftext,multilabel_clf_label,disorder,text,multiclass_clf_label,depression_label,anxiety_label,few_shot_prompt_depression,exemplar_labels_depression,results_depression_mental_llama_chat_7b
0,0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",The assigned label for this post is No. Reason...
1,1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","No, the poster does not suffer from depression..."
2,2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nPost: I'm not sure if the poster suffers fro...
3,3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression. Reaso..."
4,4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression.\n\nRe..."
5,5,8qs81x,People judge my situation too much while knowi...,"""You're not trying hard enough to improve your...","[1, 0]",{'depressive_disorder'},People judge my situation too much while knowi...,Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nThe emotional indicators in this post align ...
6,6,dpx3i2,I want to die..,(15F) \r\n \r\n Ive always wanted to..that has...,"[1, 0]",{'depressive_disorder'},I want to die. 15F Ive always wanted to.that h...,Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression.\n\nPo..."
7,7,ez4lqg,im so lethargic,(16f)for the past week i cant seem to have the...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",im so lethargic. 16ffor the past week i cant s...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nPost: i am suffering from depression. i am e...
8,8,c32kf6,Never been so unhealthy mentally and physically.,(18m) About 5 months ago I was the happiest an...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Never been so unhealthy mentally and physicall...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression.\n\nRe..."
9,9,dx4nn5,What haunts you?(a thread if you want to add t...,(23f if anyone cares) My mom mentally and emot...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",What haunts you?a thread if you want to add to...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nReasoning: The poster's history of mental an...
10,10,8q4fbu,Boss trying to make me present at a conference,"(Background: diagnosed with GAD, depression, p...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Boss trying to make me present at a conference...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['No, the poster does not suffer from depressi...","No, the poster does not suffer from depression..."
11,11,858cbk,Everything feels so wrong now.,(For all intents and purposes) My name is Dev....,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Everything feels so wrong now. For all intents...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nThe poster suffers from depression.\n\nReaso...
12,12,dty4lv,I am done,(I am 17yo)\r\n \r\n I have dated one very bea...,"[0, 0]",{'control_group'},I am done. I am 17yo I have dated one very bea...,Normal,0,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","\nReasoning for the label of ""Depression"":\n\n..."
13,13,bws4gr,"I don't like myself, even though I know I should","(I am seeing a therapist, but I just need to v...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","I dont like myself, even though I know I shoul...",Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","\nPost: Yes, the poster suffers from depressio..."
14,14,caro6p,I dont like it when people say they are depressed,(I Know this is a contoversial topic) but anyw...,"[1, 0]",{'depressive_disorder'},I dont like it when people say they are depres...,Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nReasoning for the labels assigned:\n\n1. Yes...
15,15,5s5zle,Advice with medication/how to better describe ...,(I posted this in another sub Reddit but I tho...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Advice with medicationhow to better describe s...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nThe label assigned to this post is Depressio...
16,16,avbgr5,Attempted to get HIV/AIDS,(Im a gay guy by the way) I was contemplating ...,"[1, 0]",{'depressive_disorder'},Attempted to get HIVAIDS. Im a gay guy by the ...,Depression,1,0,\nYou will be presented with a post and an ass...,"['No, the poster does not suffer from depressi...","No, the poster does not suffer from depression..."
17,17,9kezif,Ive been refusing treatment for a decade,(On mobile so bear with me)\r\n \r\n I tried c...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Ive been refusing treatment for a decade. On m...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression. Reaso..."
18,18,6dvr4n,"Thanks social anxiety, I want to die even more...",(See my last post for details)\r\n \r\n I didn...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Thanks social anxiety, I want to die even more...",Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","\nPost: Yes, the poster suffers from depressio..."
19,19,cha2ht,Just feeling empty,[17 M] I've lived the year doing my best to tr...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Just feeling empty. 17 M Ive lived the year do...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression.\n\nRe..."

In [2]:
seed=2
data_type = "depression"
df = pd.read_csv(f"../results/few_shot/few_shot_{data_type}_mental_llama_chat_7b_num_examples_ss_2_v{seed}_seed_{seed}.csv")
df

,index,id,title,selftext,multilabel_clf_label,disorder,text,multiclass_clf_label,depression_label,anxiety_label,few_shot_prompt_depression,exemplar_labels_depression,results_depression_mental_llama_chat_7b
0,0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression. The m..."
1,1,ar89pm,Anybody hate spring/summer?,".....And even so, when depression is not too s...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Anybody hate springsummer. And even so, when d...",Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression."
2,2,5g4v1n,So I'm staring at this tablet of Lexapro...,...and I'm not sure what to do. I guess I don'...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",So Im staring at this tablet of Lexapro. and I...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression. Reaso..."
3,3,9x8h3g,"Found a poem sort of thing, very emo (ha ha ha...","""I am delicate and bitter. I am sweet on the o...","[1, 0]",{'depressive_disorder'},"Found a poem sort of thing, very emo ha ha ha ...",Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","\nPost: This is a very difficult one, as the p..."
4,4,es440i,You don't get it,"""It gets better"" ""Stop thinking about it"" ""get...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",You dont get it. It gets better Stop thinking ...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","\nPost: Yes, the poster suffers from depressio..."
5,5,8qs81x,People judge my situation too much while knowi...,"""You're not trying hard enough to improve your...","[1, 0]",{'depressive_disorder'},People judge my situation too much while knowi...,Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression.\n\nTh..."
6,6,dpx3i2,I want to die..,(15F) \r\n \r\n Ive always wanted to..that has...,"[1, 0]",{'depressive_disorder'},I want to die. 15F Ive always wanted to.that h...,Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression.\n\nRe..."
7,7,ez4lqg,im so lethargic,(16f)for the past week i cant seem to have the...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",im so lethargic. 16ffor the past week i cant s...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression.\n\nRe..."
8,8,c32kf6,Never been so unhealthy mentally and physically.,(18m) About 5 months ago I was the happiest an...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Never been so unhealthy mentally and physicall...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nI would conclude that the poster suffers fro...
9,9,dx4nn5,What haunts you?(a thread if you want to add t...,(23f if anyone cares) My mom mentally and emot...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",What haunts you?a thread if you want to add to...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nPost: I often feel pain when I think about m...
10,10,8q4fbu,Boss trying to make me present at a conference,"(Background: diagnosed with GAD, depression, p...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Boss trying to make me present at a conference...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nReasoning: The poster mentions being diagnos...
11,11,858cbk,Everything feels so wrong now.,(For all intents and purposes) My name is Dev....,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Everything feels so wrong now. For all intents...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nThe label for this post is 'Yes'. Reasoning:...
12,12,dty4lv,I am done,(I am 17yo)\r\n \r\n I have dated one very bea...,"[0, 0]",{'control_group'},I am done. I am 17yo I have dated one very bea...,Normal,0,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nThis post shows no signs of depression. Reas...
13,13,bws4gr,"I don't like myself, even though I know I should","(I am seeing a therapist, but I just need to v...","[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","I dont like myself, even though I know I shoul...",Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nReasoning: The post includes multiple statem...
14,14,caro6p,I dont like it when people say they are depressed,(I Know this is a contoversial topic) but anyw...,"[1, 0]",{'depressive_disorder'},I dont like it when people say they are depres...,Depression,1,0,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...","Yes, the poster suffers from depression.\n\nRe..."
15,15,5s5zle,Advice with medication/how to better describe ...,(I posted this in another sub Reddit but I tho...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Advice with medicationhow to better describe s...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nPost: ive been diagnosed with major depressi...
16,16,avbgr5,Attempted to get HIV/AIDS,(Im a gay guy by the way) I was contemplating ...,"[1, 0]",{'depressive_disorder'},Attempted to get HIVAIDS. Im a gay guy by the ...,Depression,1,0,\nYou will be presented with a post and an ass...,"['No, the poster does not suffer from depressi...",\nThe poster shows clear signs of depression. ...
17,17,9kezif,Ive been refusing treatment for a decade,(On mobile so bear with me)\r\n \r\n I tried c...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Ive been refusing treatment for a decade. On m...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nThis post demonstrates a high level of emoti...
18,18,6dvr4n,"Thanks social anxiety, I want to die even more...",(See my last post for details)\r\n \r\n I didn...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}","Thanks social anxiety, I want to die even more...",Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['No, the poster does not suffer from depressi...","Yes, the poster suffers from depression. The p..."
19,19,cha2ht,Just feeling empty,[17 M] I've lived the year doing my best to tr...,"[1, 1]","{'depressive_disorder', 'anxiety_disorder'}",Just feeling empty. 17 M Ive lived the year do...,Comorbid (Depression + Anxiety),1,1,\nYou will be presented with a post and an ass...,"['Yes, the poster suffers from depression.', '...",\nThere is no depression label applicable for ...